name: Build App

permissions:
  contents: write

on:
  push:
    branches:
      - evan/electron-vite-migration

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Build Dependencies (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak-builder elfutils dpkg fakeroot

      - name: Setup Flatpak (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Install Dependencies
        run: bun install --development --frozen-lockfile

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: bun run build:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: bun run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: bun run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
