name: Build App

permissions:
  contents: write

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Build Dependencies (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak-builder elfutils dpkg fakeroot

      - name: Setup Flatpak (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Install Electron
        run: |
          bun remove electron --lockfile-only
          bun install https://github.com/castlabs/electron-releases#v35.3.0+wvcus

      - name: Install Dependencies
        run: bun install --development --frozen-lockfile

      - name: Install Castlabs EVS
        run: python3 -m pip install --upgrade castlabs-evs

      - name: Login to Castlabs EVS
        continue-on-error: true
        run: python3 -m castlabs_evs.account --no-ask reauth -A $ACCOUNT_NAME -P $PASSWD
        env:
          ACCOUNT_NAME: ${{ secrets.CASTLABS_EVS_ACCOUNT_NAME }}
          PASSWD: ${{ secrets.CASTLABS_EVS_PASSWORD }}

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: bun run build:linux -p never

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: bun run build:mac -p never

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: bun run build:win -p never

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
            dist/*.flatpak
